import Document, { Html, Head, Main, NextScript } from "next/document";

class MyDocument extends Document {
  static async getInitialProps(ctx) {
    const initialProps = await Document.getInitialProps(ctx);
    return { ...initialProps };
  }

  render() {
    return (
      <Html>
        <Head>
          <link rel="icon" href="%PUBLIC_URL%/favicon.ico" />
          <link rel="apple-touch-icon" href="%PUBLIC_URL%/logo192.png" />
          <link
            href="http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700&subset=all"
            rel="stylesheet"
            type="text/css"
          />
          <link
            href="../assets/global/plugins/font-awesome/css/font-awesome.min.css"
            rel="stylesheet"
            type="text/css"
          />
          <link
            href="../assets/global/plugins/simple-line-icons/simple-line-icons.min.css"
            rel="stylesheet"
            type="text/css"
          />
          <link
            href="../assets/global/plugins/bootstrap/css/bootstrap.min.css"
            rel="stylesheet"
            type="text/css"
          />
          <link
            href="../assets/global/plugins/bootstrap-switch/css/bootstrap-switch.min.css"
            rel="stylesheet"
            type="text/css"
          />
          <link
            href="../assets/global/plugins/morris/morris.css"
            rel="stylesheet"
            type="text/css"
          />
          <link
            href="../assets/global/plugins/jqvmap/jqvmap/jqvmap.css"
            rel="stylesheet"
            type="text/css"
          />
          <link
            href="../assets/global/css/components-md.min.css"
            rel="stylesheet"
            id="style_components"
            type="text/css"
          />
          <link
            href="../assets/global/css/plugins-md.min.css"
            rel="stylesheet"
            type="text/css"
          />
          <link
            href="../assets/global/plugins/select2/css/select2.min.css"
            rel="stylesheet"
            type="text/css"
          />
          <link
            href="../assets/global/plugins/select2/css/select2-bootstrap.min.css"
            rel="stylesheet"
            type="text/css"
          />
          <link
            href="../assets/global/css/components-md.min.css"
            rel="stylesheet"
            id="style_components"
            type="text/css"
          />
          <link
            href="../assets/global/css/plugins-md.min.css"
            rel="stylesheet"
            type="text/css"
          />
          <link
            href="../assets/layouts/layout4/css/layout.min.css"
            rel="stylesheet"
            type="text/css"
          />
          <link
            href="../assets/layouts/layout4/css/themes/default.min.css"
            rel="stylesheet"
            type="text/css"
            id="style_color"
          />
          <link
            href="../assets/layouts/layout4/css/custom.min.css"
            rel="stylesheet"
            type="text/css"
          />
          <link
            href="../assets/pages/css/todo.css"
            rel="stylesheet"
            type="text/css"
          />{" "}
          <link
            href="../assets/pages/css/login-5.min.css"
            rel="stylesheet"
            type="text/css"
          />
          <link
            href="../assets/pages/css/cssimg.css"
            rel="stylesheet"
            type="text/css"
          />{" "}
          <link
            href="../assets/pages/css/pricing.min.css"
            rel="stylesheet"
            type="text/css"
          />
          <link rel="shortcut icon" href="favicon.ico" />{" "}
          <link
            href="../assets/global/plugins/fullcalendar/fullcalendar.min.css"
            rel="stylesheet"
            type="text/css"
          />{" "}
          <link
            href="../assets/pages/css/login-5.min.css"
            rel="stylesheet"
            type="text/css"
          />{" "}
          <link
            href="../assets/pages/css/profile.min.css"
            rel="stylesheet"
            type="text/css"
          />{" "}
          <link
            href="../assets/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.css"
            rel="stylesheet"
            type="text/css"
          />{" "}
          <link
            href="../assets/global/plugins/datatables/datatables.min.css"
            rel="stylesheet"
            type="text/css"
          />
          <link
            href="../assets/global/plugins/bootstrap-switch/css/bootstrap-switch.min.css"
            rel="stylesheet"
            type="text/css"
          />
        </Head>
        <body class="page-header-fixed page-sidebar-closed-hide-logo page-container-bg-solid page-content-white page-md">
          <div class="page-wrapper">
            <Main />
            <NextScript />
          </div>{" "}
          <script
            src="../assets/global/plugins/jquery.min.js"
            type="text/javascript"
          ></script>
          <script src="http://code.jquery.com/jquery-1.11.0.min.js"></script>
          <script
            src="../assets/global/plugins/bootstrap/js/bootstrap.min.js"
            type="text/javascript"
          ></script>{" "}
          <script
            src="../assets/pages/scripts/todo.js"
            type="text/javascript"
          ></script>
          <script
            src="../assets/global/plugins/js.cookie.min.js"
            type="text/javascript"
          ></script>
          <script
            src="../assets/global/plugins/jquery-slimscroll/jquery.slimscroll.min.js"
            type="text/javascript"
          ></script>
          <script
            src="../assets/global/plugins/jquery.blockui.min.js"
            type="text/javascript"
          ></script>
          <script
            src="../assets/global/plugins/bootstrap-switch/js/bootstrap-switch.min.js"
            type="text/javascript"
          ></script>
          <script
            src="../assets/global/plugins/morris/morris.min.js"
            type="text/javascript"
          ></script>
          <script
            src="../assets/global/plugins/morris/raphael-min.js"
            type="text/javascript"
          ></script>
          <script
            src="../assets/global/plugins/counterup/jquery.waypoints.min.js"
            type="text/javascript"
          ></script>
          <script
            src="../assets/global/plugins/amcharts/amcharts/amcharts.js"
            type="text/javascript"
          ></script>{" "}
          <script
            src="../assets/global/plugins/amcharts/amcharts/serial.js"
            type="text/javascript"
          ></script>
          <script
            src="../assets/global/plugins/amcharts/amcharts/pie.js"
            type="text/javascript"
          ></script>
          <script
            src="../assets/global/plugins/amcharts/amcharts/radar.js"
            type="text/javascript"
          ></script>
          <script
            src="../assets/global/plugins/amcharts/amcharts/themes/light.js"
            type="text/javascript"
          ></script>
          <script
            src="../assets/global/plugins/amcharts/amcharts/themes/patterns.js"
            type="text/javascript"
          ></script>
          <script
            src="../assets/global/plugins/amcharts/amcharts/themes/chalk.js"
            type="text/javascript"
          ></script>
          <script
            src="../assets/global/plugins/amcharts/ammap/ammap.js"
            type="text/javascript"
          ></script>
          <script
            src="../assets/global/plugins/amcharts/ammap/maps/js/worldLow.js"
            type="text/javascript"
          ></script>
          <script
            src="../assets/global/plugins/amcharts/amstockcharts/amstock.js"
            type="text/javascript"
          ></script>
          <script
            src="../assets/global/plugins/horizontal-timeline/horizontal-timeline.js"
            type="text/javascript"
          ></script>
          <script
            src="../assets/global/plugins/flot/jquery.flot.min.js"
            type="text/javascript"
          ></script>
          <script
            src="../assets/global/plugins/flot/jquery.flot.resize.min.js"
            type="text/javascript"
          ></script>
          <script
            src="../assets/global/plugins/flot/jquery.flot.categories.min.js"
            type="text/javascript"
          ></script>
          <script
            src="../assets/global/plugins/jquery-easypiechart/jquery.easypiechart.min.js"
            type="text/javascript"
          ></script>
          <script
            src="../assets/global/plugins/jquery.sparkline.min.js"
            type="text/javascript"
          ></script>
          <script
            src="../assets/global/plugins/jqvmap/jqvmap/jquery.vmap.js"
            type="text/javascript"
          ></script>
          <script
            src="../assets/global/plugins/jqvmap/jqvmap/maps/jquery.vmap.russia.js"
            type="text/javascript"
          ></script>
          <script
            src="../assets/global/plugins/jqvmap/jqvmap/maps/jquery.vmap.world.js"
            type="text/javascript"
          ></script>
          <script
            src="../assets/global/plugins/jqvmap/jqvmap/maps/jquery.vmap.europe.js"
            type="text/javascript"
          ></script>
          <script
            src="../assets/global/plugins/jqvmap/jqvmap/maps/jquery.vmap.germany.js"
            type="text/javascript"
          ></script>
          <script
            src="../assets/global/plugins/jqvmap/jqvmap/maps/jquery.vmap.usa.js"
            type="text/javascript"
          ></script>
          <script
            src="../assets/global/scripts/app.min.js"
            type="text/javascript"
          ></script>
          <script
            src="../assets/pages/scripts/dashboard.min.js"
            type="text/javascript"
          ></script>
          <script
            src="../assets/layouts/layout4/scripts/layout.min.js"
            type="text/javascript"
          ></script>
          <script
            src="../assets/layouts/layout4/scripts/demo.min.js"
            type="text/javascript"
          ></script>
          <script
            src="../assets/layouts/global/scripts/quick-sidebar.min.js"
            type="text/javascript"
          ></script>
          <script
            src="../assets/layouts/global/scripts/quick-nav.min.js"
            type="text/javascript"
          ></script>
          <script
            src="../assets/global/scripts/app.min.js"
            type="text/javascript"
          ></script>{" "}
          <script
            src="../assets/global/plugins/jqvmap/jqvmap/data/jquery.vmap.sampledata.js"
            type="text/javascript"
          ></script>{" "}
          <script
            src="../assets/global/plugins/jquery-repeater/jquery.repeater.js"
            type="text/javascript"
          ></script>
          <script
            src="../assets/pages/scripts/form-repeater.min.js"
            type="text/javascript"
          ></script>{" "}
          <script
            src="../assets/global/plugins/jquery-inputmask/jquery.inputmask.bundle.min.js"
            type="text/javascript"
          ></script>
          <script
            src="../assets/global/plugins/jquery.input-ip-address-control-1.0.min.js"
            type="text/javascript"
          ></script>
          <script
            src="../assets/pages/scripts/form-input-mask.min.js"
            type="text/javascript"
          ></script>{" "}
          <script
            src="../assets/pages/scripts/table-datatables-buttons.min.js"
            type="text/javascript"
          ></script>{" "}
          <script
            src="../assets/global/scripts/datatable.js"
            type="text/javascript"
          ></script>
          <script
            src="../assets/global/plugins/datatables/datatables.min.js"
            type="text/javascript"
          ></script>{" "}
          <script
            src="../assets/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.js"
            type="text/javascript"
          ></script>{" "}
          <script
            src="../assets/global/plugins/backstretch/jquery.backstretch.min.js"
            type="text/javascript"
          ></script>{" "}
          <script
            src="../assets/global/plugins/jquery-validation/js/jquery.validate.min.js"
            type="text/javascript"
          ></script>
          <script
            src="../assets/global/plugins/jquery-validation/js/additional-methods.min.js"
            type="text/javascript"
          ></script>
          <script
            src="../assets/global/plugins/select2/js/select2.full.min.js"
            type="text/javascript"
          ></script>
          <script
            src="../assets/global/plugins/backstretch/jquery.backstretch.min.js"
            type="text/javascript"
          ></script>{" "}
          <script
            src="../assets/global/scripts/app.min.js"
            type="text/javascript"
          ></script>
        </body>
      </Html>
    );
  }
}

export default MyDocument;
